I.2 Dữ liệu kiểu ndarray

Thực hành Bài 1, 2, dùng dữ liệu kiểu ndarray (numpy)

Giả sử bạn theo dõi số tiền (đơn vị nghìn đồng) trong hóa đơn điện thoại
hàng tháng theo thứ tự từ tháng 1 đến tháng 12 trong năm vừa qua như sau:

198  185  223  221  207  203  180  195  222  177  214  216

a. Nhập dữ liệu thành một vec tơ có tên tien_dt.

In [1]:
import numpy as np

In [2]:
# tạo mảng 1 chiều
tien_dt=np.array([198, 185, 223, 221, 207, 203, 180, 195, 222, 177, 214, 216])

In [ ]:
type(tien_dt) # kiểu dữ liệu

numpy.ndarray

In [ ]:
tien_dt.ndim # Xem số chiều của mảng

1

In [ ]:
tien_dt.shape # Xem cấp của mảng

(12,)

In [ ]:
len (tien_dt) # Số phần tử của mảng 1 chiều

12

In [ ]:
a=np.array([[1,2,3],[2,3,4]]) # tạo mảng 2 chiều
a.ndim

2

In [ ]:
a.shape

(2, 3)

In [ ]:
len(a) # số phần tử của a, a có 2 phần tử, mỗi phần tử là một mảng 1 chiều gồm 3 phần tử

2

In [ ]:
# Hiển thị giá trị ở chỉ số (index) 2 (chú ý index tính từ 0, index là 2 tức là quan sát thứ 3 trong dãy)
tien_dt[2]

223

In [ ]:
tien_dt[-2] # phần tử thứ 2 tính từ cuối

214

In [ ]:
tien_dt[-6::2] # các phần tử thứ 6, 4, 2 tính từ cuối (start:end:step)

array([180, 222, 214])

In [ ]:
# Tạo mảng gồm các phần tử ở chỉ số từ 2 đến 5 (slice)
t25 = tien_dt[2:6]
print(t25)

[223 221 207 203]


In [ ]:
# Tạo mảng gồm các phần tử có index là 1,3,5,7 (slice)
t1 = tien_dt[1:8:2] # start:end:step
print(t1)

[185 221 203 195]


In [ ]:
#Tạo mảng gồm các phần tử có index chẵn (số thứ tự lẻ, index đánh số từ 0)
tle = tien_dt[0:(len(tien_dt)+1):2]
print(tle)

[198 223 207 180 222 214]


In [ ]:
# index của một giá trị cụ thể
a=np.array([2,2,4,6,7])
np.where(a==2)

(array([0, 1], dtype=int64),)

Vậy giá trị 2 xuất hiện ở 2 vị trí có index là 0 và 1

In [ ]:
# Xóa bớt phần tử của mảng
a=np.array([1,2,3,3,4,4,4,5])
print(a)

[1 2 3 3 4 4 4 5]


In [ ]:
# Xóa một giá trị cụ thể
a1=np.delete(a,np.where(a==4))
print(a1)

[1 2 3 3 5]


In [ ]:
# Xóa theo index
b1=np.delete(a,[2,4]) # Xóa các phần tử có index 2, 4
print(b1)

[1 2 3 4 4 5]


b. Tính tổng số tiền bạn phải trả cho phí điện thoại trong năm đó.

In [ ]:
np.sum(tien_dt)

2441

c. Cho biết tháng nào có số tiền ít (nhiều) nhất và số tiền là bao nhiêu?

In [ ]:
max(tien_dt)

223

In [ ]:
min(tien_dt)

177

In [ ]:
np.where(tien_dt==max(tien_dt))

(array([2], dtype=int64),)

Tháng 3 (index là 2) có số tiền lớn nhất

In [ ]:
np.where(tien_dt==min(tien_dt))

(array([9], dtype=int64),)

d. Cho biết những tháng bạn phải trả hơn 200 nghìn tiền điện thoại. Có bao nhiêu
tháng như thế?

In [ ]:
t200=np.where(tien_dt>200)
print(t200)

(array([ 2,  3,  4,  5,  8, 10, 11], dtype=int64),)


In [ ]:
len(t200[0]) # đếm số tháng thỏa mãn

7

e. Tính xem có bao nhiêu tháng mà tiền điện thoại không quá 190 nghìn.

In [ ]:
t190=np.where(tien_dt <= 190)
print(t190)

(array([1, 6, 9], dtype=int64),)


e1. Tạo ra một mảng con (slice) gồm các quan sát <= 190

In [ ]:
ds = tien_dt[np.where(tien_dt <= 190)]
print(ds)

[185 180 177]


In [ ]:
# hoặc
tien_dt[tien_dt <= 190]

array([185, 180, 177])

f. Tính xem có bao nhiêu tháng mà tiền điện thoại dao động trong khoảng
[190, 210] nghìn.

In [ ]:
td1 = np.where((tien_dt <= 210) & (tien_dt >= 190))
print(td1)

(array([0, 4, 5, 7], dtype=int64),)


In [4]:
#Lọc ra các quan sát thỏa mãn điều kiện
tien_dt[(tien_dt <= 210) & (tien_dt >= 190)]

array([198, 207, 203, 195])

In [ ]:
len(td1[0])

4

g. Tính số tiền điện thoại trung bình một tháng.

In [ ]:
np.mean(tien_dt)

203.41666666666666

Bài 3. Dùng dữ liệu tien_dt trên để thực hiện tiếp những yêu cầu sau:

a. Sửa tiền điện thoại tháng 2 thành 175.

In [ ]:
print(tien_dt)

[198 185 223 221 207 203 180 195 222 177 214 216]


In [ ]:
tien_dt[1]=175
print(tien_dt)

[198 175 223 221 207 203 180 195 222 177 214 216]


b. Nhập thêm vào dãy trên tiền điện thoại của 3 tháng tiếp theo nhưng bạn quên
mất số tiền tháng thứ 13, biết tháng thứ 14, 15 số tiền lần lượt là 201, 185.
Sau đó tính lại số tiền trung bình bạn phải trả mỗi tháng.

In [ ]:
them=np.array([None,201,185])
tiendt_15th=np.concatenate((tien_dt,them))
print(tiendt_15th)

[198 175 223 221 207 203 180 195 222 177 214 216 None 201 185]


In [ ]:
np.mean(tiendt_15th) # bị lỗi do có số liệu trống => Phải loại bỏ số liệu trống

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

In [ ]:
tiendt_14th = np.delete(tiendt_15th,np.where(tiendt_15th== None)) # loại số liệu trống
np.mean(tiendt_14th)

201.21428571428572